### ISSUE TITLE
Is sourcing 1900 required?

### ISSUE THREAD

**Issue by coolaj86** [indutny/node-nat-upnp#11]
In your code you source port 1900 explicitly for the SSDP search for the gateway. Part of what I'm trying to determine empirically with https://github.com/indutny/node-nat-upnp/issues/10 is whether that's arbitrary or if 1900 MUST be used as the source port for SSDP to work.

Sending to port 1900 as a requirement makes sense, but I thought UDP responses go back to the port number in the message received by the router.

**Comment by indutny** [comment]
I think routers are sending announcements to multicast 1900 port. So yeah, it MUST be used.

**Comment by coolaj86** [comment]
So they don't respond to the M-SEARCH, but rather broadcast?

So, to your knowledge, there's no method for having two applications listening for SSDP messages on the same machine?

**Comment by indutny** [comment]
@coolaj86 I'm afraid I don't know this details anymore :) I was working on this thing quite long time ago, sorry!

**Comment by coolaj86** [comment]
Hey, I dove into this a bit and found that the responses to multicast requests go to whichever port the request came from, as I had initially thought.

See
  * https://coolaj86.com/articles/adventures-in-upnp-with-node-js/
  * https://coolaj86.com/articles/adventures-in-upnp-on-osx/
  * https://coolaj86.com/articles/adventures-in-upnp-with-curl-and-netcat/

I'll put in a pull request to make this dynamic.

**Comment by indutny** [comment]
Nice!
